name: Roses in the Alley
favicon: null
layout_spectrum: 0.25211
typography_spectrum: 0.5737929733004421
title: Roses in the Alley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262320'
    - '#f3f2f0'
    - '#ccc7c1'
    - '#4c4e49'
    - '#a4a49a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
