name: Roses in the Alley
favicon: null
layout_spectrum: 0.612256686668843
typography_spectrum: 0.5737929733004421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06285904976539314
  lightness: 0.6354517180006951
  saturation: 0.3580426771659404
  rhythmicContrast: 0.5000498916488141
purpose: []
